### ISSUE TITLE
mts_setValuesForKeysWithDictionary not thread-safe

### ISSUE THREAD

**Issue by jpmhouston** [mobilejazz/Motis#17]
I've been seeing occasional crashes "error for object 0x7fbf1b42bbb0: pointer being freed was not allocated" in places like the `dictionary[typeAttribute] = isClassType;` line of `mts_isClassTypeTypeAttribute`.

Searching the web for `NSMutableDictionary "pointer being freed was not allocated"` found http://stackoverflow.com/a/16976032 warning about "mutating the dictionary's contents on different threads at the same time", and I see that our app is indeed calling `mts_setValuesForKeysWithDictionary` from within several occurrences of a `dispatch_async(dispatch_get_global_queue(..)` block.

Can I get any tips for making `mts_setValuesForKeysWithDictionary` thread safe? I see several category methods in NSObject+Motis.m that use a `static NSMutableDictionary` to cache results for the same type, optimizations I can either disable or make thread-safe. Is there anything more subtle I also need to look at?

**Comment by vilanovi** [comment]
Hello @R1ckye ,

Sorry for the delay. Version 1.0.2 Thread Safe of Motis is already available in Cocoa Pods.

Please, test int and report any issue you find. I've been testing and I could not reproduce anymore any crash caused by non thread safe calls to dictionaries.

Now, it still pending optimize a bit the synchronization done. I'll schedule it as my next task.

Thanks,

**Comment by vilanovi** [comment]
Hello @samkaufman and @jpmhouston,

I've seen you have forked Motis and modified it to make it thread safe. For your information, Motis is from 1.0.2 now Thread Safe (and still using the objective-c runtime cache layer).

Feel free to pull changes to your forked repository.

Cheers,

Joan

**Comment by samkaufman** [comment]
@vilanovi This is fantastic. Thanks, Joan. Very happy to have the introspection result caches back.

**Comment by vilanovi** [comment]
@samkaufman You are welcome!. And my apologies for the delay of solving this issue. I've been traveling and I could not do it before. ;)
